controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

velocity_controller:
  ros__parameters:
    joints:
      - crane_x7_shoulder_fixed_part_pan_joint
      - crane_x7_shoulder_revolute_part_tilt_joint
      - crane_x7_upper_arm_revolute_part_twist_joint
      - crane_x7_upper_arm_revolute_part_rotate_joint
      - crane_x7_lower_arm_fixed_part_joint
      - crane_x7_lower_arm_revolute_part_joint
      - crane_x7_wrist_joint
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
      - effort