controller_manager:
  ros__parameters:
    update_rate: 250  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    # gripper_controller:
    #   type: joint_trajectory_controller/JointTrajectoryController

joint_trajectory_controller:
  ros__parameters:
    joints:
      - crane_x7_shoulder_fixed_part_pan_joint
      - crane_x7_shoulder_revolute_part_tilt_joint
      - crane_x7_upper_arm_revolute_part_twist_joint
      - crane_x7_upper_arm_revolute_part_rotate_joint
      - crane_x7_lower_arm_fixed_part_joint
      - crane_x7_lower_arm_revolute_part_joint
      - crane_x7_wrist_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity