crane_x7_mpc:
  ros__parameters:
    dt: 0.0025
    T: 0.5
    N: 20
    nthreads: 2
    niter: 2
    barrier: 0.1

    config_cost:
      q_weight: 0.001
      v_weight: 0.01
      a_weight: 0.001
      u_weight: 0.0
      qf_weight: 0.01
      vf_weight: 0.001

    task_3d_cost:
      q_weight: 10
      qf_weight: 10

    task_6d_cost:
      q_trans_weight: 10
      q_rot_weight: 10
      qf_transe_weight: 10
      qf_rot_weight: 10